apiVersion: v1
kind: Service
metadata:
  name: rq-monitor-edge
  labels:
    name: rq-monitor-edge
    env: edge
    version: 0.0.1
spec:
  ports:
    - port: 9181
      targetPort: 9181
      protocol: TCP
      name: http
  selector:
    name: rq-monitor
    env: edge
